apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vms.kcli.karmalabs.local
spec:
  group: kcli.karmalabs.local
  version: v1
  scope: Namespaced
  names:
    plural: vms
    singular: vm
    kind: Vm
apiVersion: apiextensions.k8s.io/v1beta1
---
kind: CustomResourceDefinition
metadata:
  name: plans.kcli.karmalabs.local
spec:
  group: kcli.karmalabs.local
  version: v1
  scope: Namespaced
  names:
    plural: plans
    singular: plan
    kind: Plan
