apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: machines.kcli.karmalabs.local
spec:
  group: kcli.karmalabs.local
  version: v1
  scope: Namespaced
  names:
    plural: machines
    singular: machine
    kind: Machine
